/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrollRouteImport } from './routes/scroll'
import { Route as LoadMoreRouteImport } from './routes/load-more'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsAddRouteImport } from './routes/products/add'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as CategoryCategorySlugRouteImport } from './routes/category/$categorySlug'

const ScrollRoute = ScrollRouteImport.update({
  id: '/scroll',
  path: '/scroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadMoreRoute = LoadMoreRouteImport.update({
  id: '/load-more',
  path: '/load-more',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAddRoute = ProductsAddRouteImport.update({
  id: '/products/add',
  path: '/products/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/load-more': typeof LoadMoreRoute
  '/scroll': typeof ScrollRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/add': typeof ProductsAddRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/load-more': typeof LoadMoreRoute
  '/scroll': typeof ScrollRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/add': typeof ProductsAddRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/load-more': typeof LoadMoreRoute
  '/scroll': typeof ScrollRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/add': typeof ProductsAddRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/load-more'
    | '/scroll'
    | '/category/$categorySlug'
    | '/products/$productId'
    | '/products/add'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/load-more'
    | '/scroll'
    | '/category/$categorySlug'
    | '/products/$productId'
    | '/products/add'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/load-more'
    | '/scroll'
    | '/category/$categorySlug'
    | '/products/$productId'
    | '/products/add'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadMoreRoute: typeof LoadMoreRoute
  ScrollRoute: typeof ScrollRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsAddRoute: typeof ProductsAddRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scroll': {
      id: '/scroll'
      path: '/scroll'
      fullPath: '/scroll'
      preLoaderRoute: typeof ScrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/load-more': {
      id: '/load-more'
      path: '/load-more'
      fullPath: '/load-more'
      preLoaderRoute: typeof LoadMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/add': {
      id: '/products/add'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof ProductsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadMoreRoute: LoadMoreRoute,
  ScrollRoute: ScrollRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsAddRoute: ProductsAddRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
